using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Moq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TestGeneratorConsole.TestSourceFiles2;

namespace TestGeneratorConsole.TestSourceFiles2.Test
{
    [TestClass]
    public class NotSimpleClass2Test
    {
        private NotSimpleClass2 notSimpleClass2TestInstance; 

        [TestInitialize]
        public void TestInitialize()
        {
            ITestClassInterface myTestInterface = new Mock<ITestClassInterface>();
            notSimpleClass2TestInstance = new NotSimpleClass2(myTestInterface.Object);
        }

        [TestMethod]
        public void GetInterfaceTest()
        {
            ITestClassInterface actual = notSimpleClass2TestInstance.GetInterface(); 

            ITestClassInterface expected = new Mock<ITestClassInterface>();
            Assert.AreEqual(expected.Object, actual);
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void SetInterfaceTest()
        {
            ITestClassInterface classInterface = new Mock<ITestClassInterface>(); 

            Assert.Fail("autogenerated");
        }
    }
}